### ISSUE TITLE
some bug in inference_mask

### ISSUE THREAD

**Issue by kelizhong** [magic282/MXNMT#3]
In https://github.com/magic282/MXNMT/blob/046d56b958ad2c6ec0ab9e6814a8cdf1aa4c7b94/nmt/inference_mask.py#L11, 

the code should be:
init_h = mx.sym.FullyConnected(data=encoded, num_hidden=t_num_hidden* t_num_lstm_layer,
                                   weight=init_weight, bias=init_bias, name='init_fc')

**Comment by magic282** [comment]
I have been using single layer LSTM so I did not find this out. Thank you for pointing this out.
